[application]

[web.app]

# HTML title tag content
title = "password-manager"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.github.th3oth3rjak3"
publisher = "Jake Hathaway"
icon = ["assets/lock.png"]
